### PR TITLE
bump version, add sarge dependency

### LINKED ISSUE #10: How to debug problem?
I have two identical raspi setups, one for each of two printers.  This plugin works on one raspi and not the other even though I copied the working settings to the other printer.  How can I chase this problem?

P.S.  A test button would be most welcome.

### PR DESCRIPTION
**Pull request by tedder**
fixes #10

### CODE REVIEW

**Comment by shadycuz** [comment]
Do we need to update the change log? How about updating the picture in the reademe? I can help with this stuff this weekend =)

**Comment by tedder** [comment]
screenshot shouldn't require updating, I can do the changelog if you'd like. any more should prob wait 'til this weekend for you.

**Comment by tedder** [comment]
aaactually, I don't even see a changelog.

**Comment by shadycuz** [comment]
Yup =). Looks good.

**Pull request merged**
