### PR TITLE
Bugfix: uploads.im is down.

### LINKED ISSUE #6: Stopped sending images after a few days.
So I stopped getting images after a few days.

```
2018-01-24 11:08:23,635 - octoprint.server.util.sockjs - INFO - Client connection closed: 10.20.30.42
2018-01-24 13:17:41,021 - octoprint.util.comm - INFO - Finished in 10589.761 s.
2018-01-24 13:17:41,028 - octoprint.plugins.smsnotifier - INFO - Taking Snapshot.... Say Cheese!
2018-01-24 13:17:41,201 - octoprint.plugins.smsnotifier - INFO - Processing /tmp/tmp8VIy0p.jpg before uploading.
2018-01-24 13:17:46,392 - octoprint.plugins.smsnotifier - WARNING - Could not send a webcam image, sending only text notification.
2018-01-24 13:17:51,838 - octoprint.plugins.smsnotifier - INFO - Print notification sent to 6144075061
2018-01-24 13:17:51,840 - octoprint.plugins.smsnotifier - WARNING - Could not get a image from the webcam. Is it enabled?
```
When it was working.

```
2018-01-22 10:29:02,105 - octoprint.plugins.smsnotifier - INFO - Taking Snapshot.... Say Cheese!
2018-01-22 10:29:03,113 - octoprint.plugins.smsnotifier - INFO - Processing /tmp/tmpXNerJ6.jpg before uploading.
2018-01-22 10:29:08,487 - octoprint.plugins.smsnotifier - INFO - Snapshot uploaded to to http://sk.uploads.im/uZ9IN.jpg
2018-01-22 10:29:17,072 - octoprint.plugins.smsnotifier - INFO - Print notification sent to 61XXXXXXX
```

I'm going to look into it when I get time.

### PR DESCRIPTION
**Pull request by shadycuz**
Uploads.im is down. Probably for good. Returning 500 with no msg. Not just the API but the website as well. Fixes #6 

I have signed up for a cloudinary free account under the "Octoprint-Twilio" Moniker. I can share the creds with you if you like.

Last time you updated the py package to `0.3.0` but did not set that in `setup.py`. I have the set the version in setup.py to `0.3.1`. 

Thanks,
Levi

### CODE REVIEW

**Comment by taxilian** [comment]
I've invited you as a collaborator on the project; I don't have a lot of time to work on this right now and you seem to know what you're doing =]

**Comment by shadycuz** [comment]
@taxilian I think you will still have to push the pypi releases.

```
Creating tar archive
removing 'OctoPrint-Twilio-0.3.1' (and everything under it)
running upload
Submitting dist/OctoPrint-Twilio-0.3.1.tar.gz to https://upload.pypi.org/legacy/
Upload failed (403): The user 'shadycuz' is not allowed to upload to project 'OctoPrint-Twilio'.
```

**Comment by taxilian** [comment]
Finally getting to this.  I actually did bump the versions in setup.py, I just forgot to `git push` =] Easily disstracted, I guess.

I've made you a maintainer for the project on pypi; I'll try to remember how to submit this. I don't submit things to pypi very often (Just this, in fact) so I have to relearn each time.

**Comment by taxilian** [comment]
I think I figured it out, but next time you can do it yourself if you need =] At this point you've done as much original coding as I have.

Just as a point of interest, the main feature I've considered adding that I haven't yet is support for sending the text using a google voice account.

**Comment by shadycuz** [comment]
Hmm, do they have an API? So we create the account and people only need to
enter a recipient number? I really like this idea. I'll look into the API
part and probably make a new repo. The only issue is privacy. We would know
everyone's phone number.

**Comment by taxilian** [comment]
https://github.com/pettazz/pygooglevoice

http://sphinxdoc.github.io/pygooglevoice/

I haven't played with it in awhile, but if I remember correctly you needed to do something to log in on the console and it'd save the creds in your home directory; after that it would all just work.

No reason we'd need to collect any information from people for this to work, the config would all be on their system.

**Comment by tedder** [comment]
Please don't remove the Twilio support when doing this.

**Comment by shadycuz** [comment]
Separate plugin =)

**Comment by shadycuz** [comment]
@taxilian So I looked at the API. It doesn't support MMS, though we could still pass on the link to the person. We could implement MMS our selves and Submit a PR. 

The real issue is how many people are using just voice? For instance my google voice is integrated with my google hangouts, so this new plugin would not work for me.

**Comment by taxilian** [comment]
... huh.  are you sure? Granted, my main gvoice number I've been using since before it was owned by Google, back when it was GrandCentral, but even new accounts I've set up I can send and receive SMS messages through. I haven't tried all of them through the pygooglevoice API, though.

if you go to voice.google.com do you not have a phone number and such?

My thought was that if you didn't have google voice you could just set up a gvoice account, but this is the first inkling I've heard that it might not be compatible with some gvoice accounts.

**Comment by shadycuz** [comment]
@taxilian You can send MMS with google voice ;) but not with the python library.  https://github.com/pettazz/pygooglevoice/issues/50

I have a google voice number, but I can't use the google voice api to use it because I have it integrated into hangouts. I'm guessing most users will have it integrated into hangouts but that might be changing https://www.usatoday.com/story/tech/columnist/2017/01/29/best-android-messaging-apps-crowded-field/97155226/ . Any new accounts just for the new plugin would work fine.

image

**Comment by taxilian** [comment]
Interesting.  I suspect that a lot of android users do that, but probably only them. Additionally, I would tend to lean towards making a google voice account just for this purpose rather than using an existing account -- but then, I use my google voice number as a "home phone" number that we give people.

Regardless, seems like it should be useful... particularly since my twilio trial has ended and I'm not sure it's worth paying for just for this.

**Comment by shadycuz** [comment]
I'll get a new voice number and try to reverse engineer the Google API for
mms.

**Pull request merged**
