### PR TITLE
Fix sarge import

### PR DESCRIPTION
**Pull request by MisterGlass**
Fix for #13

### CODE REVIEW

**Comment by taxilian** [comment]
I no longer use this plugin, though I created it; can anyone else test this and let me know if it's working for them? If a second person confirms that this fixes the issue then I'll merge it.  @shadycuz you still helping?

**Comment by MisterGlass** [comment]
Perhaps someone else can take over as maintainer? I have been pondering adding a"delay" feature, the plugin keeps taking a photo before my extruder parks itself to the side, while my extruder is blocking the view of the part.

**Comment by shadycuz** [comment]
@taxilian @MisterGlass I have been wondering if I should upgrade to the latest pi. I will pick one up and do a fresh install on it.

**Comment by taxilian** [comment]
I have no objection to someone else taking over as the maintainer; @shadycuz has been mostly doing that, but sounds like he's been busy as well.  @MisterGlass are you volunteering to join the team?

**Comment by MisterGlass** [comment]
@taxilian Happy to lend a hand, though someone will have to send me a tutorial on the proper way to load other repos as the plugin in octoprint. I think I ended up finding the installed files & manually patching them to test this change ;)

**Pull request merged**
